In [16]:
import yfinance as yf
from datetime import date
from datetime import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
#Select the Stock by name
stock_selection = input("Select one stock: ")
stock_selection
stock = yf.Ticker(stock_selection)

Select one stock: TSLA


In [15]:
#About the stock
stock.info

{'regularMarketPrice': None,
 'preMarketPrice': None,
 'logo_url': '',
 'trailingPegRatio': 1.2868}

# Date

In [4]:
 date_from = str(input("Select the date from where yo want in format YY-MM-DD: \n example(22-01-01) "))

Select the date from where yo want in format YY-MM-DD: 
 example(22-01-01) 22-01-01


In [5]:
#take selected date, converted into datetime then into an integer array
#.astype() change the format of the array
datetime_from = datetime.strptime(date_from, '%y-%m-%d')
datetime_date = datetime_from.strftime('%Y-%m-%d')
np_datetime = np.array(datetime_date.split("-"))
np_datetime = np_datetime.astype(int)
np_datetime

array([2022,    1,    1])

In [6]:
#take todays date, converted into datetime then into an integer array
#.astype() change the format of the array
today = datetime.now()
today_date = today.strftime('%Y-%m-%d')
today_date.split("-")
np_today = np.array(today_date.split("-"))
np_today = np_today.astype(int)
np_today

array([2023,    1,   21])

In [7]:
difference = np_today - np_datetime
difference

array([ 1,  0, 20])

In [8]:
numbers = difference[1] + 1

if difference[0] >= 1:
    numbers += 12 * difference[0] + 1 

print(numbers)
    


14


# Dividends

In [9]:
#Show the dividends from the selected date to today
dividends = stock.dividends[numbers:-1]

dividends_df = pd.DataFrame(dividends)

print(f"Last {numbers -1} dividends for stock {stock_selection} are: \n",dividends_df)

Last 13 dividends for stock KO are: 
                            Dividends
Date                                
1965-09-09 00:00:00-04:00   0.002214
1965-11-26 00:00:00-05:00   0.002214
1966-03-14 00:00:00-05:00   0.002474
1966-06-09 00:00:00-04:00   0.002474
1966-09-09 00:00:00-04:00   0.002474
...                              ...
2021-09-14 00:00:00-04:00   0.420000
2021-11-30 00:00:00-05:00   0.420000
2022-03-14 00:00:00-04:00   0.440000
2022-06-14 00:00:00-04:00   0.440000
2022-09-15 00:00:00-04:00   0.440000

[228 rows x 1 columns]


# Prices

In [10]:
#Take historical prices from de selected date to todays date
stock_historical = yf.download(tickers = stock_selection, start = datetime_date, period = '5d', interval = '5m' )
stock_historical = stock_historical.round(2)
stock_historical = stock_historical[['Close']]
stock_historical

[*********************100%***********************]  1 of 1 completed

1 Failed download:
- KO: 5m data not available for startTime=1641013200 and endTime=1674304647. The requested range must be within the last 60 days.


Empty DataFrame
Columns: [Close]
Index: []

In [11]:
stock_data = stock_historical.describe()
stock_data

Close
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN

In [12]:
stock_mean = stock_data.iloc[1]
print(f"The mean of the last {numbers} months is: \n", stock_mean)

The mean of the last 14 months is: 
 Close   NaN
Name: mean, dtype: float64


In [13]:
#Most recent price
last_price = stock_historical.iloc[-1]
print(f"The most recent price for stock {stock_selection} is: \n", last_price)

IndexError: single positional indexer is out-of-bounds

# Visualizations

In [ ]:
plt.plot(stock_historical)
plt.title(f'stock {stock_selection}')